version: "3.8"
services:
  db:
    container_name: wordle-db
    build: ./db
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wordle
    restart: always
    ports:
      - "3306:3306"
  api:
    container_name: wordle-api
    build: .
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: db
      MYSQL_PORT: ${DB_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure