AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ContainerRepositoryName:
    Type: String
    Default: wordle-coderty-app

Resources:
  ContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ContainerRepositoryName